using AutoMapper;
using challenge1.Common.EmailService.Classes;
using challenge1.Common.EmailService.Classes.Interfaces;
using challenge1.Common.EmailService.Data;
using challenge1.Common.EmailService.DTOs;
using challenge1.Common.EmailService.Models;
using challenge1.Common.EmailService.Repositories.Interfaces;
using challenge1.Common.EmailService.Services.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace challenge1.Common.EmailService.Services
{
    internal class EmailService : IEmailService
    {
        private readonly EmailDbContext _context;
        private readonly IMapper _mapper;
        private readonly ILogging _logging;
        private readonly IEmailRepository _emailRepository;
        private readonly IEmailAttachmentService _emailAttachmentService;
        private readonly IEmailLogService _emailLogService;
        private readonly IEmailSender _emailSender;
        private readonly IBackgroundEmailQueue _backgroundEmailQueue;

        public EmailService(EmailDbContext context, IMapper mapper, ILogging logging, IEmailRepository emailRepository, IEmailAttachmentService emailAttachmentService, IEmailLogService emailLogService, IEmailSender emailSender, IBackgroundEmailQueue backgroundEmailQueue)
        {
            _context = context;
            _mapper = mapper;
            _logging = logging;
            _emailRepository = emailRepository;
            _emailAttachmentService = emailAttachmentService;
            _emailLogService = emailLogService;
            _emailSender = emailSender;
            _backgroundEmailQueue = backgroundEmailQueue;
        }

        /// <summary>
        /// Retrieves emails that are pending and eligible to be processed by the batch job.
        /// </summary>
        /// <param name="request">The request containing filtering criteria.
        /// If <see cref="GetPendingBatchEmailsRequestDTO.ModuleType"/> is provided, only emails matching that module type will be retrieved.
        /// </param>
        /// <returns>
        /// A list of <see cref="GetPendingBatchEmailsResponseDTO"/> instances representing pending emails,
        /// or <c>null</c> if no emails could be retrieved.
        /// </returns>
        public async Task<List<GetPendingBatchEmailsResponseDTO>?> GetPendingBatchEmailsAsync(GetPendingBatchEmailsRequestDTO? request)
        {
            Email email = new();
            if (request != null)
            {
                email.ModuleType = request.ModuleType;
            }
            var emails = await _emailRepository.GetBatchJobPendingEmailsAsync(email);
            return _mapper.Map<List<GetPendingBatchEmailsResponseDTO>?>(emails);
        }

        /// <summary>
        /// Creates and sends an email immediately based on the provided manual send request.
        /// </summary>
        /// <param name="request">
        /// The <see cref="SendManualEmailRequestDTO"/> containing:
        /// - Creator information (<see cref="SendManualEmailRequestDTO.CreatedById"/> and <see cref="SendManualEmailRequestDTO.CreatedByName"/>),
        /// - Optional list of attachments to persist,
        /// - Optional <see cref="SendManualEmailRequestDTO.MaxRecipientsPerBatch"/> to split recipients.
        /// </param>
        /// <returns>
        /// <see cref="SendManualEmailResponseDTO.EmailId"/> containing the persisted email identifier when the send operation succeeds;
        /// otherwise <see cref="SendManualEmailResponseDTO.ErrorMessage"/> containing Error Message if the operation fails at any step.
        /// </returns>
        public async Task<SendManualEmailResponseDTO> SendManualEmailAsync(SendManualEmailRequestDTO request)
        {
            bool updateEmailResponse;
            SendManualEmailResponseDTO responseDTO = new();

            try
            {
                var context = new ValidationContext(request);
                Validator.ValidateObject(request, context, validateAllProperties: true);

                Email? emailResponse = null;
                try
                {
                    var email = _mapper.Map<Email>(request);
                    //emailId will be auto generated by efcore
                    email.SendType = Constant.SendType.Manual;
                    email.Status = Constant.EmailStatus.Pending;
                    email.CreatedDate = DateTime.Now;

                    emailResponse = await _emailRepository.AddEmailAsync(email);
                    if (emailResponse == null)
                    {
                        responseDTO.ErrorMessage = "Failed to add email record.";
                        return responseDTO;
                    }
                    if (request.Attachments != null && request.Attachments.Any())
                    {
                        foreach (var attachment in request.Attachments)
                        {
                            var addAttachmentResponseDTO = await _emailAttachmentService.AddEmailAttachmentAsync(attachment);
                            if (addAttachmentResponseDTO == null)
                            {
                                throw new Exception($"Failed to add attachment to email. EmailId: {emailResponse.EmailId}, Attachment FileName: {attachment.FileName}");
                            }
                            else if (!string.IsNullOrEmpty(addAttachmentResponseDTO.ErrorMessage))
                            {
                                throw new Exception($"Failed to add attachment to email. EmailId: {emailResponse.EmailId}, Attachment FileName: {attachment.FileName}, Error: {addAttachmentResponseDTO.ErrorMessage}");
                            }
                        }
                    }

                    //Send the email immediately
                    _backgroundEmailQueue.QueueEmail(async token =>
                    {
                        await _emailSender.SendEmailAsync(
                            emailResponse.Subject,
                            emailResponse.Body,
                            emailResponse.Recipients,
                            emailResponse.Cc,
                            emailResponse.Bcc,
                            _mapper.Map<List<AttachmentDTO>>(emailResponse.Attachments),
                            request.MaxRecipientsPerBatch);
                    });

                    emailResponse.SentAt = DateTime.Now;
                    emailResponse.Status = Constant.EmailStatus.Sent;

                    return _mapper.Map<SendManualEmailResponseDTO>(emailResponse);
                }
                catch (Exception ex)
                {
                    //no transaction rollback needed. If exception occurs, the email won't be sent and status will be updated to Failed.
                    if (emailResponse != null)
                    {
                        emailResponse.Status = Constant.EmailStatus.Failed;
                        //log error in db
                        var emailLogRequest = new AddEmailLogRequestDTO
                        {
                            EmailId = emailResponse.EmailId,
                            LogType = Constant.EmailLogType.Error,
                            LogMessage = ex.Message,
                            CreatedById = request.CreatedById,
                            CreatedByName = request.CreatedByName
                        };
                        var emailLogResponse = await _emailLogService.AddEmailLogAsync(emailLogRequest);
                        if (emailLogResponse == null)
                        {
                            _logging.LogBllError("Failed to add Email Log.");
                        }
                    }

                    responseDTO.ErrorMessage = ex.Message;
                }
                finally
                {
                    if (emailResponse != null)
                    {
                        emailResponse.UpdatedById = EmailServiceSettings.BatchJobId;
                        emailResponse.UpdatedByName = EmailServiceSettings.BatchJobName;
                        emailResponse.UpdatedDate = DateTime.Now;

                        updateEmailResponse = await _emailRepository.UpdateEmailAsync(emailResponse);
                        if (!updateEmailResponse)
                        {
                            throw new Exception($"Failed to update email. EmailId: {emailResponse.EmailId}");
                        }
                    }
                }
            }
            catch (ValidationException vex)
            {
                responseDTO.ErrorMessage = vex.Message;
            }
            catch (Exception ex) //Outer catch to catch finally exception
            {
                _logging.LogBllError(ex.ToString());
                responseDTO.ErrorMessage = ex.Message;
            }

            return responseDTO;
        }

        /// <summary>
        /// Creates and queues batch emails based on the provided requests.
        /// </summary>
        /// <param name="requests">
        /// The <see cref="List{T}"/> of <see cref="SendBatchEmailRequestDTO"/> containing:
        /// - Creator information (<see cref="SendBatchEmailRequestDTO.CreatedById"/> and <see cref="SendBatchEmailRequestDTO.CreatedByName"/>),
        /// - Optional list of attachments to persist,
        /// - Optional <see cref="SendBatchEmailRequestDTO.MaxRecipientsPerBatch"/> to split recipients.
        /// </param>
        /// <returns>
        /// A <see cref="SendBatchEmailResponseDTO.BatchGroupId"/> containing the current batch of email group id when the send operation succeeds, caller can use for retrieve or delete batch email purpose.
        /// Otherwise <see cref="SendBatchEmailResponseDTO.ErrorMessage"/> containing Error Message if the operation fails at any step.
        /// </returns>
        public async Task<SendBatchEmailResponseDTO> SendBatchEmailsAsync(List<SendBatchEmailRequestDTO> requests)
        {
            SendBatchEmailResponseDTO responseDTO = new();

            await using var transaction = await _context.Database.BeginTransactionAsync();
            try
            {
                var context = new ValidationContext(requests);
                Validator.ValidateObject(requests, context, validateAllProperties: true);

                var batchGroupId = Guid.NewGuid(); // Batch Group Id for the current batch of emails
                foreach(var request in requests)
                {
                    var email = _mapper.Map<Email>(request);
                    //emailId will be auto generated by efcore
                    email.BatchGroupId = batchGroupId;
                    email.SendType = Constant.SendType.BatchJob;
                    email.Status = Constant.EmailStatus.Pending;
                    email.CreatedDate = DateTime.Now;

                    var emailResponse = await _emailRepository.AddEmailAsync(email);
                    if (emailResponse == null)
                    {
                        responseDTO.ErrorMessage = "Failed to add email record.";
                        return responseDTO;
                    }
                    if (request.Attachments != null && request.Attachments.Any())
                    {
                        foreach (var attachment in request.Attachments)
                        {
                            var addAttachmentResponseDTO = await _emailAttachmentService.AddEmailAttachmentAsync(attachment);
                            if (addAttachmentResponseDTO == null)
                            {
                                throw new Exception($"Failed to add attachment to email. EmailId: {emailResponse.EmailId}, Attachment FileName: {attachment.FileName}");
                            }
                            else if (!string.IsNullOrEmpty(addAttachmentResponseDTO.ErrorMessage))
                            {
                                throw new Exception($"Failed to add attachment to email. EmailId: {emailResponse.EmailId}, Attachment FileName: {attachment.FileName}, Error: {addAttachmentResponseDTO.ErrorMessage}");
                            }
                        }
                    }
                }

                responseDTO.BatchGroupId = batchGroupId;

                await transaction.CommitAsync();
            }
            catch (ValidationException vex)
            {
                responseDTO.ErrorMessage = vex.Message;
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                responseDTO.ErrorMessage = ex.Message;

                _logging.LogBllError(ex.ToString());
            }

            return responseDTO;
        }

        /// <summary>
        /// Cancels all pending emails associated with the specified BatchGroupId.
        /// </summary>
        /// <param name="request">
        /// The request containing the BatchGroupId to cancel.
        /// </param>
        /// <returns>
        /// A response indicating the success or failure of the cancellation.
        /// </returns>
        public async Task<CancelPendingBatchEmailsResponseDTO> CancelPendingBatchEmailsAsync(CancelPendingBatchEmailsRequestDTO request, CancellationToken cancellationToken = default)
        {
            CancelPendingBatchEmailsResponseDTO responseDTO = new();
            try
            {
                var pendingEmails = await _emailRepository.GetBatchJobPendingEmailsAsync(new Email { BatchGroupId = request.BatchGroupId }, cancellationToken);
                if (pendingEmails == null || !pendingEmails.Any())
                {
                    responseDTO.IsSuccess = false;
                    responseDTO.ErrorMessage = "No pending emails found for the specified BatchGroupId.";
                    return responseDTO;
                }
                foreach (var email in pendingEmails)
                {
                    email.Status = Constant.EmailStatus.Cancelled;
                    email.CancelReason = request.CancelReason;
                    email.UpdatedById = request.UpdatedById;
                    email.UpdatedByName = request.UpdatedByName;
                    email.UpdatedDate = DateTime.Now;
                }
                responseDTO.IsSuccess = await _emailRepository.UpdateEmailsAsync(pendingEmails, cancellationToken);
                return responseDTO;
            }
            catch (Exception ex)
            {
                _logging.LogBllError(ex.ToString());

                responseDTO.IsSuccess = false;
                responseDTO.ErrorMessage = ex.Message;
                return responseDTO;
            }
        }

        /// <summary>
        /// Triggers the sending of batch emails. Processes all pending emails in the batch job queue.
        /// </summary>
        /// <returns>
        /// A boolean indicating whether the batch email send was successful.
        /// </returns>
        public async Task<bool> TriggerBatchEmailsSendAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                var pendingEmails = await _emailRepository.GetBatchJobPendingEmailsAsync(null, cancellationToken);
                if (pendingEmails == null || !pendingEmails.Any())
                {
                    return true; // No pending emails to process
                }

                // Process only emails whose TargetSendDate is due
                var emailsToUpdate = new List<Email>();
                foreach (var email in pendingEmails.Where(x => x.TargetSendDate <= DateTime.Now))
                {
                    try
                    {
                        _backgroundEmailQueue.QueueEmail(async token =>
                        {
                            await _emailSender.SendEmailAsync(
                                email.Subject,
                                email.Body,
                                email.Recipients,
                                email.Cc,
                                email.Bcc,
                                _mapper.Map<List<AttachmentDTO>>(email.Attachments),
                                EmailServiceSettings.MaxRecipientsPerBatch);
                        });
                        email.SentAt = DateTime.Now;
                        email.Status = Constant.EmailStatus.Sent;
                    }
                    catch (Exception ex)
                    {
                        email.Status = Constant.EmailStatus.Failed;
                        var emailLogRequest = new AddEmailLogRequestDTO
                        {
                            EmailId = email.EmailId,
                            LogType = Constant.EmailLogType.Error,
                            LogMessage = ex.Message,
                            CreatedById = email.CreatedById,
                            CreatedByName = email.CreatedByName
                        };
                        var emailLogResponse = await _emailLogService.AddEmailLogAsync(emailLogRequest, cancellationToken);
                        if (emailLogResponse == null)
                        {
                            _logging.LogBllError("Failed to add Email Log.");
                        }
                    }
                    email.UpdatedById = EmailServiceSettings.BatchJobId;
                    email.UpdatedByName = EmailServiceSettings.BatchJobName;
                    email.UpdatedDate = DateTime.Now;
                    emailsToUpdate.Add(email);
                }
                
                if (emailsToUpdate.Any())
                {
                    await _emailRepository.UpdateEmailsAsync(emailsToUpdate, cancellationToken);
                }
                return true;
            }
            catch (Exception ex)
            {
                _logging.LogBllError(ex.ToString());
                return false;
            }
        }

        /// <summary>
        /// Retries sending failed batch emails. 
        /// If retry is successful, updates status to Sent; otherwise, logs the error. 
        /// Retry count is incremented for each attempt until maximum retries is reached.
        /// </summary>
        /// <returns>A boolean indicating whether the retry was successful.</returns>
        public async Task<bool> RetryFailedBatchEmailsAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                var failedEmails = await _emailRepository.GetFailedBatchEmailsAsync(cancellationToken);
                if (failedEmails == null || !failedEmails.Any())
                {
                    return true; // No failed emails to process
                }
                
                var emailsToUpdate = new List<Email>();
                foreach (var email in failedEmails)
                {
                    try
                    {
                        _backgroundEmailQueue.QueueEmail(async token =>
                        {
                            await _emailSender.SendEmailAsync(
                                email.Subject,
                                email.Body,
                                email.Recipients,
                                email.Cc,
                                email.Bcc,
                                _mapper.Map<List<AttachmentDTO>>(email.Attachments),
                                EmailServiceSettings.MaxRecipientsPerBatch);
                        }); 
                        email.SentAt = DateTime.Now;
                        email.Status = Constant.EmailStatus.Sent;
                    }
                    catch (Exception ex)
                    {
                        // Log error in db
                        email.Status = Constant.EmailStatus.Failed;
                        var emailLogRequest = new AddEmailLogRequestDTO
                        {
                            EmailId = email.EmailId,
                            LogType = Constant.EmailLogType.Error,
                            LogMessage = ex.Message,
                            CreatedById = email.CreatedById,
                            CreatedByName = email.CreatedByName
                        };
                        var emailLogResponse = await _emailLogService.AddEmailLogAsync(emailLogRequest, cancellationToken);
                        if (emailLogResponse == null)
                        {
                            _logging.LogBllError("Failed to add Email Log.");
                        }
                    }
                    email.RetryCount++;
                    email.UpdatedById = EmailServiceSettings.BatchJobId;
                    email.UpdatedByName = EmailServiceSettings.BatchJobName;
                    email.UpdatedDate = DateTime.Now;
                    emailsToUpdate.Add(email);
                }
                
                if (emailsToUpdate.Any())
                {
                    await _emailRepository.UpdateEmailsAsync(emailsToUpdate, cancellationToken);
                }
                return true;
            }
            catch (Exception ex)
            {
                _logging.LogBllError(ex.ToString());
                return false;
            }
        }
    }
}
