using AutoMapper;
using challenge1.Common.EmailService.Classes;
using challenge1.Common.EmailService.Classes.Interfaces;
using challenge1.Common.EmailService.DTOs;
using challenge1.Common.EmailService.Models;
using challenge1.Common.EmailService.Repositories.Interfaces;
using challenge1.Common.EmailService.Services.Interfaces;

namespace challenge1.Common.EmailService.Services
{
    internal class EmailAttachmentService : IEmailAttachmentService
    {
        private readonly IMapper _mapper;
        private readonly ILogging _logging;
        private readonly IS3Helper _s3Helper;
        private readonly IUtilities _utilities;
        private readonly IEmailAttachmentRepository _emailAttachmentRepository;

        public EmailAttachmentService(IMapper mapper, ILogging logging, IS3Helper s3Helper, IUtilities utilities, IEmailAttachmentRepository emailAttachmentRepository)
        {
            _mapper = mapper;
            _logging = logging;
            _s3Helper = s3Helper;
            _utilities = utilities;
            _emailAttachmentRepository = emailAttachmentRepository;
        }

        public async Task<AddAttachmentResponseDTO?> AddEmailAttachmentAsync(AddAttachmentRequestDTO request)
        {
            try
            {
                var emailAttachment = _mapper.Map<EmailAttachment>(request);
                //emailAttachmentId will be auto generated by efcore

                if (request.AttachmentType == AttachmentTypeEnum.Database && request.Content != null)
                {
                    emailAttachment.FileSize = request.Content.Length;
                }
                else if (request.AttachmentType == AttachmentTypeEnum.S3 && !string.IsNullOrEmpty(request.AttachmentLocation))
                {
                    var s3Info = _utilities.ParseS3Path(request.AttachmentLocation);
                    var metadata = await _s3Helper.GetS3FileMetadataAsync(s3Info.bucketName, s3Info.key);
                    if (metadata != null)
                    {
                        emailAttachment.FileSize = metadata.ContentLength;
                    }
                    else
                    {
                        return new AddAttachmentResponseDTO { ErrorMessage = "Failed to retrieve S3 file." };
                    }
                }

                emailAttachment.EmailId = request.EmailId;
                emailAttachment.CreatedById = request.CreatedById;
                emailAttachment.CreatedByName = request.CreatedByName;
                emailAttachment.CreatedDate = DateTime.Now;

                var response = await _emailAttachmentRepository.AddEmailAttachmentAsync(emailAttachment);
                if (response == null)
                {
                    return null;
                }

                return _mapper.Map<AddAttachmentResponseDTO>(response);
            }
            catch (Exception ex)
            {
                _logging.LogBllError(ex.ToString());
                return null;
            }
        }
    }
}
